import java.io.*;  
import java.net.*; 
import java.util.*; 
import java.util.ArrayList;
import java.util.Scanner;
class Myserver 
{ 
     public static void main(String[] args) throws Exception
    {  
      ServerSocket ss=new ServerSocket(8080);
      Socket s=ss.accept();
      DataInputStream dinput=new DataInputStream(s.getInputStream());
      DataOutputStream doutput=new DataOutputStream(s.getOutputStream());
      String str="***Welcome to food ordering System***",str1="List of Available foods given below:",Availablefood="***1.VEG 2.NONVEG 3.milkshakes***",select="SELECT THE TYPE OF FOOD:";
      String ch,list1,select1,name,phone,address;
      int amt;
      String item1="1.Chicken Briyani - Rupees=150 ";
      String item2=" 2.Mutton Briyani - Rupees=180 "; 
      String item3=" 3.Chilli chicken - Rupees=100 ";
      String item4=" 4.Parota(2pcs) - Rupees=30 ";  
      String item5=" 5.shawarma - Rupees=80 ";
      String item6=" 6.Dosa - Rupees=50 ";
      String item7=" 7.Poori - Rupees=30 "; 
      String item8=" 8.Pongal - Rupees=50 ";
      String item9=" 9.Vadai(2pcs) - Rupee 20 ";  
      String item10=" 10.Poori(2pcs) -Rupee=35 ";
      String item11=" 11.Chocolate Milkshakes - Rupees=100 ";
      String item12=" 12.Butterscotch MIlkshakes - Rupees=100 ";
      String item13=" 13.Oreo Milkshakes - Rupees=100 ";
      String item14=" 14.DarkFantasy milkshakes- Rupees=100 ";
      String item15=" 15.Beverages - Rupees=40 ";
      String item16=" 16.freshJuices -Rupees=40 ";
      String e="end";
      doutput.writeUTF(str);
      doutput.flush();
      doutput.writeUTF(str1);
      doutput.flush();
      doutput.writeUTF(Availablefood);
      doutput.flush();
      doutput.writeUTF(item1);
      doutput.flush();
      doutput.writeUTF(item2);
      doutput.flush();
      doutput.writeUTF(item3);
      doutput.flush();
      doutput.writeUTF(item4);
      doutput.flush();
      doutput.writeUTF(item5);
      doutput.flush();
      doutput.writeUTF(item6);
      doutput.flush();
      doutput.writeUTF(item7);
      doutput.flush();
      doutput.writeUTF(item8);
      doutput.flush();
      doutput.writeUTF(item9);
      doutput.flush();
      doutput.writeUTF(item10);
      doutput.flush();
      doutput.writeUTF(item11);
      doutput.flush();
      doutput.writeUTF(item12);
      doutput.flush();
      doutput.writeUTF(item13);
      doutput.flush();
      doutput.writeUTF(item14);
      doutput.flush();
      doutput.writeUTF(item15);
      doutput.flush();
      doutput.writeUTF(item16);
      doutput.flush();
      select1=dinput.readUTF();
      System.out.println("Order items Placed:"+select1); 
      amt=dinput.readInt();
      System.out.println("Total amount :"+amt);
      name=dinput.readUTF();
      System.out.println("Customer number:"+name);
      address=dinput.readUTF();
      System.out.println("Delivery address:"+address); 
      phone=dinput.readUTF(); 
      System.out.println("Customer phone number:"+phone);      
      s.close();
      ss.close();
}  
}  
